name: abhomies
services:
  frontend:
      build:
        context: ./www
        dockerfile: Dockerfile
      ports:
        - "3000:3000"
      depends_on:
        - backend
      networks:
        - abhomies
  backend:
      build:
        context: ./api
        dockerfile: Dockerfile
      ports:
        - "8070:8070"
      environment:
        DATABASE_URL: ${DATABASE_URL}
      depends_on:
        - db
      networks:
        - abhomies
  db:
      image: postgres:latest
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ports:
      - '5432:5432'
      volumes:
      - abhomies_db_volume:/var/lib/postgresql/data
      networks:
      - abhomies
volumes:
  abhomies_db_volume:
networks:
  abhomies:
